version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - DART_API_KEY=d63d0566355b527123f1d14cf438c84041534b2b
      - EMAIL_SENDER=dlwlrma401@gmail.com
      - EMAIL_PASSWORD=byvu_dkyn_qfyz_lwji
      - EMAIL_RECEIVER=ljm@inveski.com
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=investment_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: